In [1]:
import numpy as np

def floyd(U,R):
    n = len(U)
    r = R
    u = U
    for k in range(n):
        for i in range(n):
            for j in range(n):
                # 不断地更新路径，每次找到vi到vj最短的路径
                if U[i][j] > U[i][k] + U[k][j]:
                    u[i][j] = U[i][k] + U[k][j]
                    r[i][j] = R[i][k]
                else:
                    r[i][j] = R[i][j]
                    u[i][j] = U[i][j]
            
    return u,r

U = np.array([[0, 4, 5, 999, 999],
              [999, 0, 3, 999, 6],
              [999, 999, 0, -2, 3],
              [999, 1, 999, 0, 999],
              [-4, 999, 999, 2, 0]])

R = np.array([[1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5]])

U, R = floyd(U,R)
print(f'输出的权矩阵为：\n{U}')
print(f'输出的路径矩阵为：\n{R}')

输出的权矩阵为：
[[ 0  4  5  3  8]
 [ 2  0  3  1  6]
 [-1 -1  0 -2  3]
 [ 3  1  4  0  7]
 [-4  0  1 -1  0]]
输出的路径矩阵为：
[[1 2 3 3 3]
 [5 2 3 3 5]
 [5 4 3 4 5]
 [2 2 2 4 2]
 [1 1 1 1 5]]
